name: CI

env:
  REPO: hugsy/modern_cmdline
  VERBOSE: "1"

on: [push, pull_request]

jobs:
  ci_tests:
    name: "CI for ${{ matrix.os }}/${{ matrix.platform }}"

    strategy:
      fail-fast: false
      matrix:
        os: ['windows-latest', 'ubuntu-latest'] #, 'macos-latest']
        platform: ['x64']
        python-version: ['3.9']

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
        architecture: ${{ matrix.platform }}

    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v3.x

    - name: Initialize environment
      run: |
        python3 -m pip install --user --upgrade pip
        python3 -m pip install --user --upgrade -r requirements.txt
        mkdir ~/bin
        cd ~

    - name: Execute generic tests
      run: |
        python3 modern.py -v --search-unix ls
        python3 modern.py -v --search-rust lsd
        python3 modern.py -v --install ripgrep --dry-run
        python3 modern.py -v --install ripgrep
        python3 modern.py -v --install-all --dry-run
        python3 modern.py -v --install-all

    - name: Execute linux tests
      if: matrix.os == 'ubuntu-latest'
      run: |
        python3 modern.py -v --search-rust exa
        python3 modern.py -v --install exa
        python3 modern.py -v --install ox

    - name: Test commands - Windows
      if: matrix.os == 'windows-latest'
      run: |
        cp -Force ~/PowershellAliases.ps1 ~/bin/
        . ~/PowershellAliases.ps1
        hexdump c:\windows\system32\ntdll.dll
        cat c:\windows\win.ini

    - name: Test commands - Linux/MacOS
      if: matrix.os != 'windows-latest'
      run: |
        cp -f ~/.aliases ~/bin/
        source ~/.aliases
        hexdump /bin/ls
        cat /etc/passwd

    - name: Publish artifact
      id: publish_artifact
      uses: actions/upload-artifact@v2
      with:
        name: modern_cmdline_${{ matrix.os }}_${{ matrix.platform }}_${{ env.GITHUB_SHA_SHORT }}
        path: ~/bin
